apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-blue
  labels:
    app: httpbin-blue
spec:
  replicas: 0
  selector:
    matchLabels:
      app: httpbin
      role: blue
  template:
    metadata:
      labels:
        app: httpbin
        role: blue
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80