apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-blue
  labels:
    app: {{ .Release.Name }}-blue
spec:
  replicas: {{ .Values.replicas.blue }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      role: blue
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        role: blue
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag.blue }}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80