apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    role: test-blue
  name: {{ .Release.Name }}-blue
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
    role: blue


