apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
    role: test-green
  name: httpbin-green
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpbin
    role: green


