apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-green
  labels:
    app: {{ .Release.Name }}-green
spec:
  replicas: {{ .Values.replicas.green }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      role: green
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        role: green
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag.green }}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80