apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-green" .Release.Name }}
  labels:
    app: {{ printf "%s-green" .Release.Name }}
spec:
  replicas: {{ .Values.replicas.green }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      role: green
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        role: green
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag.green }}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80