apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    role: test-green
  name: {{ printf "%s-green" .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
    role: green


