apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      role: {{ .Values.role }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        role: {{ .Values.role }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80