apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    role: {{ .Values.prod.role }}
    env: prod
  name: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
    role: {{ .Values.prod.role }}